### ISSUE TITLE
what is best way i can handle button tap in UITableViewCell using RX.

### ISSUE THREAD

**Issue by santhoshs5** [RxSwiftCommunity/RxDataSources#119]
Thanks for great library.

I have a tableview which is having multiple cells with buttons in it.

I need to change the state of the button on tap like change image.

There is button bottom of tableview which should capture the state of the buttons present all tableview cells.As of now I am doing with state array without RX.

I want to try this implementation with RX, Could you please help me how can i do this.

**Comment by farzadshbfn** [comment]
Well I'm new to RX too, but I guess you have to store an optional disposeBag "Inside" the cell. and set a new instance on `prepareForReuse`.  and in configuringCell bind it weakly to view controller and dispose it by the DisposeBag from the cell itself. because you don't want to add a subscriber EACH time a cell is dequeued and store all of them. only the ones present on the screen.

**Comment by Alex-Alex77** [comment]
I did exactly as you told, but subscription is not disposed when I pop my view controller. Here is how  I make it inside my cell:
    class ActionsCell: UITableViewCell {
        @IBOutlet weak var myButton: UIButton!
        var bag = DisposeBag()
        override func prepareForReuse() {
            super.prepareForReuse()
            bag = DisposeBag()
        }
    }
And here is how I subscribe:
    switch dataSource[indexPath] {
        case .actionsItem:
            let cell: ActionsCell = tableView.dequeueReusableCell(forIndexPath: indexPath)
            cell.myButton.rx.tap.asDriver()
                .drive(onNext: { [weak self] in
               // code that has to be handled by view controller
               self?....
            }).disposed(by: cell.bag)
            return cell
    ....
I even tried to change the communication between action from cell and view controller using delegate, but unfortunately weak var delegate seems not helping. deinit() of the view controller is called only when I delete subscription (or delete assigning cell.delegate = self)

**Comment by farzadshbfn** [comment]
There is a cleaner way to handle this in #821 (https://github.com/ReactiveX/RxSwift/issues/821)
but your code should work fine too, i can't say what the problem is 🤔

**Comment by Alex-Alex77** [comment]
Thank you very much for response. I think I've found what the problem was. Using self this way caused retain cycle and its not obvious from the code I've shared. Here is the code to demonstrate it: 
```swift
dataSource.configureCell = { [weak self] (dataSource, tableView, indexPath, _) in
    switch dataSource[indexPath] {
        case .actionsItem:
            let cell: ActionsCell = tableView.dequeueReusableCell(forIndexPath: indexPath)
            cell.myButton.rx.tap.asDriver()
                .drive(onNext: { [weak self] in
                // code that has to be handled by view controller
                self?....
            }).disposed(by: cell.bag)
            return cell
        ....
```
I'm not sure if I need to capture [weak self] inside drive(onNext:), but adding [weak self] to the beginning of outer scope (dataSource.configureCell = { [weak self] .... ) solved the problem

**Comment by farzadshbfn** [comment]
oh, I've countered this leak before. it's not relative to RX btw. when there are nested closures, topmost outter closure must capture self as week (if needed). The reason is, "there is a block of code inside the closure" which uses self (and this closure doesn't know how that "block of code" is using it) so it captures it strongly. and answer to your next question, no you don't need to capture it weakly inside the inner closure too. remove `[weak self]`, you still have to work with `self?...`.
Glad your problem is solved ;)
