### ISSUE TITLE
What is using diff algorithm?

### ISSUE THREAD

**Issue by muukii** [RxSwiftCommunity/RxDataSources#151]
What is using diff algorithm in RxDataSouces?
I would like to know good points or bad points compared with [IGListDiff](https://github.com/Instagram/IGListKit/blob/master/Source/Common/IGListDiff.mm) (or something)

IGListDiff of IGListKit uses Paul Heckel's Diff Algorithm.
https://github.com/lxcid/ListDiff

Thanks.

**Comment by kzaher** [comment]
Hi,

I'm only superficially familiar with IGListDiff so please double check this.

I don't think they are using Paul Hackel's diff algorithm, but they are using something similar.

We are using similar algorithm to what they are using but with some differences:
* we've got support for two level section + item animations, so that's a + (I don't think they support it, like moving items between sections, etc...). Please double check this, I think they only support it in a kind of recursive way, so they'll do diff per sections. I'm not sure do and how they support dynamic number of sections.
* we've decided to not support duplicate items or sections because that would require us to have arrays per key, but they have decided to handle that case (that's a tradeoff so that's - and + depending how you look at it). In case there are duplicates we fallback to non animated refresh because that is ambiguity and invalid data as I see it.
* our structures are also set up so they can support table view editing operations out of the box. I'm assuming that's why they have those controllers in their data source, but don't have time to investigate. We can use normal `tableView.rx.item*` to update the data.

I'm hoping ours algorithm is faster than theirs, but I haven't done any benchmarks 🙈 . If it's not, challenge accepted 😆. If you have time to set up that benchmark that would be great, although they are only calculating single level, so that's a bit cheating 😆 .

Neither ours or IGListDiff will calculate minimal number of changes in all cases like some dynamic programming algorithms, but dynamic programming algorithms require O(n^2) in worst case while ours and IGListDiff require O(n) in worst case if you consider dictionary operations as O(1), and they generate pretty good results IMHO.

**Comment by muukii** [comment]
Hi,

Thank you for your answer.

Diff algorithm for TableView/CollectionView interests me.
I'll look for differences of function each library in [my playground repo](https://github.com/muukii-incubator/DiffPlayground)

And, I'm progressing the implementation little by little 😉 #149 

Thank you!

**Comment by Damonvvong** [comment]
I found that `Paul Hackel's diff algorithm` does not find the optimal edit distance between two arrays

So why not use the [Wagner Fischer algorithm](https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm)?

Although  in a large number, using `Wagner Fischer algorithm` is obviously very slow. But usually, a screen can display the number is not much.

So why not use the `Wagner Fischer algorithm` to find the optimal edit distance, but quickly find the edit distance using `Paul Hackel's diff algorithm`?
