### ISSUE TITLE
line 32 Duplicate item error and crash

### ISSUE THREAD

**Issue by vitali36** [RxSwiftCommunity/RxDataSources#194]
Hello! I have a problem with updating tableview after getting new data. Problem with Diff. Error.duplicateItem and getting rxDebugFatalError into RxTableViewSectionedAnimatedDataSource class. How can I fix it?

**Comment by AlexanderBollbach** [comment]
i'm also running into this problem.

**Comment by kzaher** [comment]
Don't create duplicate ids. The error message is pretty clear. If something is id, you can't have multiple instances with the same value.

**Comment by dkbhowell** [comment]
@kzaher Honest question: I thought the whole design of the system around RxTableViewSectionedAnimatedDataSource was based around identity and equality such that if two items have the same identity but are unequal, then the cell for that item needs to be updated. 

If you aren't allowed to have multiple instances with the same id, then how do you communicate updates to an existing item?

**Comment by kzaher** [comment]
At any given time, all items currently rendered on screen need to have
unique ids.

If some item from previous screen has the same id as some currently
presented item (that's how we can tell they are the same item), then we can
animate the transition from previous state to current.

If screens contains multiple items with same ids, and you want to animate
to next screen with those items, then we refuse do guess (and incur
performance costs) what animations did you want.

**Comment by dkbhowell** [comment]
@kzaher Got it. That makes perfect sense. Thank you!

On a related topic: is there any way to make item updates (same id, new content) work if ItemType is a Class, not a struct? As far as I can tell, equality comparisons from old version and new version both reflect the change (since they are both references to the same newly changed object).

Only solution I've found is to mimic struct behavior by replacing the original object with a mutated copy of that object. I know that ideally you would use structs, but persistence frameworks typically require classes.
