### ISSUE TITLE
Deleting All table data causes crash "Fatal error: Duplicate item [invalid object]"

### ISSUE THREAD

**Issue by guoyingtao** [RxSwiftCommunity/RxDataSources#197]
When there is only one row, when I delete all data, it is OK.
But When there is more than one row, it will crash when I delete all table data, just like the screenshot below

DataSource.swift

<img width="1114" alt="datasources_swift" src="https://user-images.githubusercontent.com/26723384/33700948-3e36571c-daea-11e7-8c6e-38ed6c634376.png">

I also got the information: "Item [invalid object] has already been indexed at (0, 0)"

**Comment by freak4pc** [comment]
@guoyingtao How are you "deleting your item" exactly

**Comment by vitali36** [comment]
I have a same problem.

**Comment by DesdeChaves** [comment]
Similar problem:

If I delete one item after one  button tap, all works fine.
 If I try to delete a bunch of itens after one tap a have a crash with the error message  "Item [invalid object] has already been indexed at "

Otherwise, If I tap a button to add a bunch of itens all works fine.

Suppose this scenario:


import Foundation
import RealmSwift
import RxDataSources

// Grade Objet
class Grade: Object  {
    @objc  dynamic var uid: Int = 0
    @objc dynamic var grade: String = ""

  override class func primaryKey() -> String? {
        return "uid"
    }
}

extension Grade: IdentifiableType {
    var identity: Int {
        return self.isInvalidated ? 0 : uid
    }
}

// Student Objet
class Student: Object  {
    @objc  dynamic var uid: Int = 0
    @objc dynamic var name: String = ""
     let grades = List\<Grade\>()

  override class func primaryKey() -> String? {
        return "uid"
    }
}

extension Student: IdentifiableType {
    var identity: Int {
        return self.isInvalidated ? 0 : uid
    }
}

In my tableView each section name is the student name and in the rows I list all grades.  If I create a action to delete all bad grades (p.e. "grade == 'F'), my application crashes  every time I tap the button. If I remove one by one, that's ok.

Is there a way to fix that, or this is a bug?

**Comment by vitali36** [comment]
I solved this problem, but this not a good solution. Try replace RxTableViewSectionedAnimatedDataSource to RxTableViewSectionedReloadDataSource. But then sections not will not be animatable like fade, top, etc. Or you can also comment this line rxDebugFatalError(e) , but the problem with custom animation still remains unresolved

**Comment by DesdeChaves** [comment]
Solved my problem too. RxTableViewSectionedReloadDataSource works well, but no animation . Thanks for you suggestion. Perhaps I need I new approach in my app.

**Comment by vitali36** [comment]
Write me please if you can resolved problem with animation

**Comment by sallyahmed** [comment]
there are any updates on that issue?

**Comment by Ravi61** [comment]
This same problem happened to me, just had to make sure every section titles and all model identities were different.

**Comment by dkbhowell** [comment]
I'm running into a similar issue as well. I'm getting the same error after simply updating a property of one of the model items. I expected an update to that cell only, with animation, but instead I get this same error and crash. I suspect this library is intended for use only with struct models, and lots of problems like this crop up when you start using class models. Unfortunately many of us use persistence frameworks that requires models to be classes. It is somewhat surprising to me that this is a problem, mainly because the framework already its own abstractions for identity and equality in place, which should enable them to make this work for both classes and structs. So I'm not sure what the problem is and I don't have a good workaround for this just yet (aside from just using the ReloadDataSource).

**Comment by freak4pc** [comment]
@dkbhowell see here @kzaher’s answer in regards to reference types not officially supported for animated reloads: https://github.com/RxSwiftCommunity/RxDataSources/pull/239#issuecomment-398163017

**Comment by kzaher** [comment]
I believe it is quite simple.

**Don't use duplicate ids**
**Don't mutate ids** (if you mutate id, it's not id) `return self.isInvalidated ? 0 : uid`
**Don't use reference types** (or if you are, be aware that you are responsible for cell content updates, we won't be able to detect changes since the previous bound item will also have the same change)

On the other hand:
**Do read messages**
If the message says, duplicate xxx, and you have duplicate xxx, fix your code.

**Comment by LYFsy** [comment]
I solved this problem, because my sectionType's identity same when sometime

**Comment by AppHock** [comment]
Hi, 
eg:AllNotesSection(header: "", modelItems: [model]) 
header value must be unique， see this photo， u will clear
![Screen Shot 2019-07-16 at 9 49 02 PM](https://user-images.githubusercontent.com/14970137/61299909-92aa7380-a813-11e9-8b92-f33c12afab73.png)

**Comment by EslamHanafy** [comment]
I solved them problem, but this not a good solution, if you are using Realm you can do something like this
    ```
typealias Identity = Int32
    
    var identity: Int32 {
        return isInvalidated ? Int32.random(in: 1000000...10000000) : id
    }
```

**Comment by alexshekhovtsov** [comment]
> I solved them problem, but this not a good solution, if you are using Realm you can do something like this
> 
> ```
> typealias Identity = Int32
>     
>     var identity: Int32 {
>         return isInvalidated ? Int32.random(in: 1000000...10000000) : id
>     }
> ```

try this:
    typealias Identity = String
    
    var identity: Identity {
        return UUID().uuidString
    }

**Comment by elesahich** [comment]
@vitali36 lots of thanks from korea 👋
