### ISSUE TITLE
Drop `Equatable` requirement from `AnimatableSectionModelType.Item`

### ISSUE THREAD

**Issue by mosamer** [RxSwiftCommunity/RxDataSources#201]
- `IdentifiableType.identity` should be used exclusively for all comparisons and changeset calculations.
- `Item` conformance to `Equatable` semantically means that `identity = self` which will not be a correct implementation in many cases (e.g. when only subset of model's properties are used by data source).
- Initial inspection of the code shows that `Equatable` is only required for array comparison, which can be replaced with `Identity`-dependent implementation.

**Comment by kzaher** [comment]
`Identity` and `Equatable` are two separate concepts that are both needed.

> Item conformance to Equatable semantically means that identity = self which will not be a correct implementation in many cases (e.g. when only subset of model's properties are used by data source).

No, that's not what identity means.

> Initial inspection of the code shows that Equatable is only required for array comparison, which can be replaced with Identity-dependent implementation.

No, it's required for row update detection logic.

**Comment by freak4pc** [comment]
@mosamer Two items could have different values so they're not equal in the sense of Equatable but they have the same Identity for the sense of deciding if a cell represents the same item on-screen. I don't think they are comparable (Equatable and Identity, that is)

**Comment by mkko** [comment]
My two cents would be that the relation between Equatable and Identity can be a bit confusing. Would it make sense to clarify in the docs? That the identity doesn't mean equality. At first I didn't even realize that `Equatable` was needed for the items (due to `NSObject`).

I just spent an hour debugging a weird side effect when removing one row and eventually learned that because of the item I was using inherited `NSObject` and already implemented `Equatable` I was allowed to use the class as it was. However, I didn't realize that recreating those items every time would cause reload on the cells. This reload was messing up the deletion animation and wasn't visible in any other way.

**Comment by kzaher** [comment]
@mkko 

There is no relation between them. Just like their interface suggests.

Equatable means are two values equal.
Identity is used to determine identity of some concept which is undefined over time and is used to uniquely identify it over time. E.g. Your identity is your tax number.  You can change the color of your hair, your name even, friends, but you will always have the same tax number.

**Comment by beeth0ven** [comment]
Hi, there.

 I think for `UITableView` (UICollectionView is the same) :

* `Identity` is used to decide whether the row should be **`insert`, `delete` or `move`** by compare the item's old `Identity` with new `Identity`.

* `Equatable` is used to decide whether the **same**  `Identity` item's row should be **`reload`**.

So, with `Identity` and  `Equatable` we could choose the right method  to update row.  E.g. `tableView.insertRows`, `tableView.deleteRows`, `tableView.moveRow`, and `tableView.reloadRows`.

**Comment by mkko** [comment]
Let's not call it relation then. Still, the mixed use of these two was confusing to me. I didn't expect (reload) animation if I replaced an unequal item with the same identity. Relation or not, I think they're connected since they both have an effect on animation.

In my case it would've been obvious if I didn't use items that had implemented equality with references. Technically I would not change a thing, but this would've been helpful to know when setting things up. The examples kind of omit the whole equality since they're using basic types.

**Comment by beeth0ven** [comment]
@mkko , Yes It can be a bit confusing at first. When i'm trying this out the first time, it was confusing me too.
It becomes more clear when i try to implement this update mechanism. So the basic question is when items changed which row should be `insert`, `delete`, `move` or `reload`. 
The `Identity` helps with `insert`, `delete`, `move`.
The `Equatable` helps with `reload `.

My understanding is very simple, the real implementation is much complicated in this library.

Maybe the most confusing thing is why `Equatable` maters?

For example: 

If i edit this comment, the old comment and new comment has the same `Identity` but they are not `equal` since the content are not `equal`. So it's better to reload this comment row so that this comment would show the latest version. And for other comments which are not edited, it means they are `equal` to previous one, so these rows don't need to be `reload`.

If we don't want the row to be `reload` when corresponding object is replaced with the same `identity` object, here is a little tricky: 

```swift
class Object: NSObject {
    let id: String

   // ...

    override func isEqual(_ object: Any?) -> Bool {
        if let other = object as? Object {
            return id == other.id
        }
        return false
    }
}
```

Hope this may help.

**Comment by freak4pc** [comment]
I agree there's no relation technically but there is a misconception of how these two are used separately by RxDataSources. 

I think it would be very easy to add a quick sentence on that in the README file, if you'd want I can easily do that.

**Comment by beeth0ven** [comment]
Agreed it's implicit and not documented, we'd better add some docs. @freak4pc thanks for your help.

**Comment by freak4pc** [comment]
I have a PR up with suggested documentation additions for this here: 
https://github.com/RxSwiftCommunity/RxDataSources/pull/239

**Comment by amirpervaiz086** [comment]
Hi guys, I am using multiple section AnimatableSectionModelType datasource and the situation is:
-> First I do flatMap to get sections
-> Each section I do flatMap to get list of videos to show horizontal scroll in each cell. 

Previously, I was using concatMap but it was slow so I changed it with FlatMap and maintaining order by using Variable Observables. The problem is when I add section it does show empty section but in second flatMap I update my section with video list and assign it to Variables which is bind to tableView. Issue is reloading of section is not happening since after update section model with video list. 

I further debug and found Equatable which is used to reload cell based on data change is having same left and right section items thats why its not reloading. Both left and right objects have videos list where as the cell on tableView is empty.

**Comment by freak4pc** [comment]
@amirpervaiz086 This doesn't seem related to this issue at all, correct me if I'm mistaken.

**Comment by amirpervaiz086** [comment]
I found this thread explaining Identity and Equatable and how Rxdatasource thinks about insertion/deletion or reload based on these two properties. I have exactly followed the same logic but somehow updating data with same identity is not reloading that cell. I found Equatable is actually having same objects (both lhs or rls) which always return true where as loaded and new updated data is not same. If I am wrong can you please explain me how Equatable is called based on what logic by datasource?

**Comment by amirpervaiz086** [comment]
@freak4pc fixed it. My bad. one of my model was accidentally defined as class not struct where it was always returning true for **Equatable** even for changes since it was by reference changing it to struct worked :)
