### ISSUE TITLE
How to use in UITableViewController?

### ISSUE THREAD

**Issue by yirankege** [RxSwiftCommunity/RxDataSources#214]
If i use the RxDataSource in UIViewController that's all right, but i wanna use it in UITableViewController,the DelegateProxyType will give me some error messages:"Hint: Maybe delegate was already set in xib or storyboard and now it's being overwritten in code.\n". i have been cancel the UITableviewController's delegate in Storyboard. then i don't know how to use the RxDataSource.

**Comment by sergdort** [comment]
HI, @yirankege. Just set it to `nit` before binding
`tableView.dataSource = nil`

**Comment by bobgodwinx** [comment]
Ok here is my review because I've ran into this problem over and over again. If you are using `UITableViewController` directly then you have this error because the `UITableViewController` initializes the `datasource` b4 the `viewDidLoad` is called. So you can use `tableView.datasource = nil` in your `viewDidLoad` and you are good to go. But if you are using a `UIViewController` + manually add or programmatically created `UITableView` then the problem doesn't appear and the is no need to make it nil. You can just do your binding directly in `viewDidLoad`.

**Comment by yirankege** [comment]
@sergdort @bobgodwinx  Thanks you very much,i've fixed this.
