### ISSUE TITLE
Deleting cell animation is different from expected.

### ISSUE THREAD

**Issue by naoto0n2** [RxSwiftCommunity/RxDataSources#216]
In Example 3, the animation when deleting a cell (`Animation 1`) is different from the expected.
Is there a workaround to animate it like `Animation 2` using RxDataSources?

| Animation 1 | Animation 2 |
| --- | --- |
| ![image1](https://user-images.githubusercontent.com/8586560/37632258-b6cd4b44-2c30-11e8-9c72-0b6579755d1f.gif) | ![image2](https://user-images.githubusercontent.com/8586560/37632398-5848bc88-2c31-11e8-818e-9153745b872a.gif) |

Both animations are reproduced on iOS 11 simulator.

**Comment by Vkt0r** [comment]
@naoto0n2 When you define the `AnimationConfiguration` you can define the type of animation you want it for the `deletion`. The differents one are exposed here:

```swift
public enum UITableViewRowAnimation : Int {

    
    case fade

    case right // slide in from right (or out to right)

    case left

    case top

    case bottom

    case none // available in iOS 3.0

    case middle // available in iOS 3.2.  attempts to keep cell centered in the space it will/did occupy

    case automatic // available in iOS 5.0.  chooses an appropriate animation style for you
}

```

**Comment by naoto0n2** [comment]
@Vkt0r 
Thanks for your suggestion.
I changed the enum value [here](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example3_TableViewEditing.swift#L68), but the animation did not change from `Animation 1` on iOS11.
Is there any other solution?

**Comment by Vkt0r** [comment]
@naoto0n2 Sorry for the delay, time flies. I was checking the issue and as far I checked everything was fine with the library regarding the call of the animation I mean. 

Is true that the animation is not working I verified that, the weird thing was it was not working only for deletion animations. So I create a new project without the library to check if was happening something in iOS 11 with the `deleteRows(at:_ , with: _)` and it does indeed. 

Since iOS 11 that method is presenting problems animating the deletion. I created a project with a few items on a `UITableView` to test the deletion and it was not working at all. I was able to fix it using a workaround posted in https://stackoverflow.com/questions/46303649/ios-11-uitableview-delete-rows-animation-bug. 

```swift
CATransaction.begin()
CATransaction.setCompletionBlock({
        self.tableView.beginUpdates()
        self.tableData.remove(at: indexPath.row)
        self.tableView.deleteRows(at: [indexPath], with: .right)
        self.tableView.endUpdates()
 })
CATransaction.commit()
```

Nevertheless fix it here it would take more time as the `_performBatchUpdates(self, changes: changes, animationConfiguration: animationConfiguration)` is called several times and the `CATransaction` breaks it if the code is inserted there. 

I think @kzaher is the best one to answer if we want to solve it now only for the deletion process or wait until Apple solve this bug that I hope can be soon.
