### ISSUE TITLE
Build failure with Carthage and Xcode 10's new build system

### ISSUE THREAD

**Issue by mattgallagher** [RxSwiftCommunity/RxDataSources#237]
It's not clear to me if this is an RxDataSources, Carthage or Xcode 10 problem but in any case...

Running a cartfile with the following entries:

```
github "ReactiveX/RxSwift" ~> 4.0
github "RxSwiftCommunity/RxDataSources" ~> 3.0
```

Results in multiple errors including:

```
Build system information
warning: unexpected duplicate XXX

Build system information
warning: unexpected mutating task XXX

Build system information
warning: duplicate output file XXX
```

The easiest workaround is to open the RxDataSources.xcodeproj and delete the RxSwift project (reference only) from the file tree. After this, the Carthage build proceeds correctly.

**Comment by bobgodwinx** [comment]
@mattgallagher This is absolutely not a `Carthage` nor `RxDataSources` problem. I've just built a `Carthage` binary from `master` using `Version 9.4 (9F1027a)` and it works. So definitely an `Xcode 10` problem. I think it has to do with new build system. There is still not much information on this: 
`File -> Workspace Settings -> Build System -> Legacy Build System`  vs  `File -> Workspace Settings -> Build System -> New Build System`

**Comment by bwhiteley** [comment]
I'm seeing this as well. Another workaround is to flip the build system in project settings to Legacy, then build with Carthage.

**Comment by rpassis** [comment]
The issue is that carthage/xcodebuild is building RxSwift twice, once as your own project dependency and then again inside the RxDataSources workspace. 

Basically the build tool is telling you that your build process is overwriting its own files, which is a good thing.

**Comment by DanielAsher** [comment]
I've just run into this. Bit of a bugger for CI systems.

**Comment by mortenbekditlevsen** [comment]
Isn't the issue that RxSwift is bundled with RxDataSources? Shouldn't the Cartfile just refer to it, but not have the full source included?
We are getting the problem on Xcode 10 (new build system) as well, but even on Xcode 9 we got some weird compiler errors. We upgraded RxSwift, but sometimes the (older) version bundled with RxDataSources would end up in some Xcode cache. 

The issue was that some API (Single.do(onNext:)) was deprecated in the new version of RxSwift (in favor of Single.do(onSuccess:)). 
But when Xcode 9 got confused about our version of RxSwift we got an old version where the new API was not present. Some of the developers kept changing the API call back and forth between 'onSuccess' and 'onNext' because of this issue. :-)

**Comment by freak4pc** [comment]
@mortenbekditlevsen Are you sure the submodule is included as a sub-project along with the Cartfile? Not sure if that's the desired behavior in this case but hard to say if this breaks support for sub-module users.

**Comment by rpassis** [comment]
RxSwift is embedded as a project inside the RxDatasource project. All that is needed is for it to be removed AFAICT.

**Comment by mortenbekditlevsen** [comment]
@freak4pc Yes, that is the behavior I see when checking out the project using Carthage. The sub module reference causes RxSwift to be checked out. 
I am not sure how one would be depending on the sub module reference. Would that be in a situation where neither Carthage, cocoapods or spm was used?
In such a situation I assume that I would still like to be in charge of checking out RxSwift myself instead of relying on it being ‘inside’ of RxDataSources. But of course someone could have other opinions about that. :-)

**Comment by mattgallagher** [comment]
The latest 3.1 build fixes the problem. Thanks!
