### ISSUE TITLE
Default Initializer for RxTableViewSectionedReloadDataSource does not exist

### ISSUE THREAD

**Issue by azamsharp** [RxSwiftCommunity/RxDataSources#253]
The default initializer for RxTableViewSectionedReloadDataSource does not exist. The initializer takes in arguments which is not mentioned in the docs.

**Comment by cozzin** [comment]
I think there is no default initializer because `configureCell` is required.
In this section, we can see that `configureCell` is a required argument and the remaining arguements are optional.

https://github.com/RxSwiftCommunity/RxDataSources#how

3) Customize closures on the dataSource as needed:
- `configureCell` (required)
- `titleForHeaderInSection`
- `titleForFooterInSection`
- etc

```swift 
dataSource.configureCell = { (ds: RxTableViewSectionedReloadDataSource<SectionOfCustomData>, tv: UITableView, ip: IndexPath, item: Item) in
  let cell = tv.dequeueReusableCell(withIdentifier: "Cell", for: ip)
  cell.textLabel?.text = "Item \(item.anInt): \(item.aString) - \(item.aCGPoint.x):\(item.aCGPoint.y)"
  return cell
}
dataSource.titleForHeaderInSection = { ds, index in
  return ds.sectionModels[index].header
}
```

**Comment by mkko** [comment]
The issue is to the point. This is from the README.md:

```swift
let dataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, Int>>()
Observable.just([SectionModel(model: "title", items: [1, 2, 3])])
    .bind(to: tableView.rx.items(dataSource: dataSource))
    .disposed(by: disposeBag)
```

I think we need to update the documentation.

**Comment by freak4pc** [comment]
@mkko Great point here - the documentation here wasn't updated for too long with the change to requesting the configureCell closure on the data source's initialization. If anyone would like to make a PR around this, I'd love to review and merge. Thanks!

**Comment by Vkt0r** [comment]
#255 address the issue.
