### ISSUE TITLE
[Proposal] Replace diffing algorithm to DifferenceKit

### ISSUE THREAD

**Issue by ra1028** [RxSwiftCommunity/RxDataSources#256]
I created a new diffing algorithm framework [DifferenceKit](https://github.com/ra1028/DifferenceKit) with referencing Heckel algorithm and RxDataSources (Differentiator).
Currently DifferenceKit is an alpha release, but I propose to replace from Differentiator after v1.0.0 release.
DifferenceKit has a little different specifications from Differentiator, but it able to get almost similar diff.
And it's faster and safer.

I think it's possible to avoid user confusion by implement the following overlay until the next major update of RxDataSources. 
```swift
public protocol IdentifiableType: Differentiable {
    associatedtype Identity: Hashable

    var identity : Identity { get }
}
public extension IdentifiableType {
    var differenceIdentiier: Identity {
        return identity
    }
}
```

If you prefer this proposal, I'll implement it in the future.

**Comment by kzaher** [comment]
Hi @ra1028 ,

I've gave some it some thought and investigated this a bit, but I don't think we would like to go this way. I don't want to add any dependency that doesn't really have compelling arguments for me to add it.

From the speed perspective it is practically the same. Maybe you've managed to gain a bit of speed here and there, but If there is a need we could improve speed further. I don't have any incentive to optimize speed since UI{Table/Collection}View is the slowest anyway, so there is no point. I don't think I've seen anybody complain that we are slow.

I'm not sure its safer. It enables you to use items with multiple ids, but this was a deliberate choice on our end. I could have also added that `Occurrence` abstraction (nicely done), but I didn't see the point since this is a bug and you are silently failing! We don't crash in prod, we just fallback to reload, so nobody should have any problems because of this behavior, and it is correct thing to do IMHO.

You are doing the same thing as we are, although I do admit that your code looks more Swifty. At the time I was writing our algorithm I didn't have the benefits of being inspired by other libraries since none really supported two level animations properly. Including IGListKit. Maybe they do now, didn't check them recently.

It took me ages just to discover a general enough way to separate animations into batches so they cover all cases without `UI{Table,Collection}View` crashing.
```swift
result.append(contentsOf: try sectionCommands.generateDeleteSectionsDeletedItemsAndUpdatedItems())

result.append(contentsOf: try sectionCommands.generateInsertAndMoveSections())

result.append(contentsOf: try sectionCommands.generateInsertAndMovedItems())
```

Maybe there are some other ways that work, hard to tell. I was too exhausted.

It seems to me that you are doing the same thing.

```swift
        // The 1st stage changeset.
        // - Includes:
        //   - section deletes
        //   - element deletes

        // The 2st stage changeset.
        // - Includes:
        //   - section inserts
        //   - section moves

        // The 3st stage changeset.
        // - Includes:
        //   - element inserts
        //   - element moves
```

It seems to me that you are also using equivalent optimizations as we are. We have 

```
    private struct OptimizedIdentity<E: Hashable> : Hashable {
        let hashValue: Int
        let identity: UnsafePointer<E>

        init(_ identity: UnsafePointer<E>) {
            self.identity = identity
            self.hashValue = identity.pointee.hashValue
        }

        static func == (lhs: OptimizedIdentity<E>, rhs: OptimizedIdentity<E>) -> Bool {
            if lhs.hashValue != rhs.hashValue {
                return false
            }

            if lhs.identity.distance(to: rhs.identity) == 0 {
                return true
            }

            return lhs.identity.pointee == rhs.identity.pointee
        }
    }
```

Although I believe that you have a bug (I've commented it below).

```swift
private struct TableKey<T: Hashable>: Hashable {
    let hashValue: Int
    private let pointer: UnsafePointer<T>

    init(pointer: UnsafePointer<T>) {
        self.hashValue = pointer.pointee.hashValue
        self.pointer = pointer
    }

    static func == (lhs: TableKey, rhs: TableKey) -> Bool {
        return lhs.hashValue == rhs.hashValue // <-- This is a bug. If hash is equal, that doesn't imply that lhs == rhs
            || lhs.pointer.distance(to: rhs.pointer) == 0
            || lhs.pointer.pointee == rhs.pointer.pointee
    }
}
```

When I look at your implementation, my general impression is that although it does look a bit more swifty in some respects, it is at best marginal improvement, so I don't think I would like to delete our implementation and spend time proving that yours works.

Although you've tried to polish your library a bit more then we have, I would say that the real diff code is equally ugly in both of them, but that's just life.

Although I don't think there are compelling reasons to make a dependency on your library, I would congratulate you on it. It's a really nice library. Maybe if it existed 3 years ago I would probably just use it.

Off the record, I am happy that I've found out about your library. I think that you are probably the second person on GitHub that has made a diffing library that:
* acknowledges that O(n) is the only reasonable complexity class for UI. Have no idea what the hell are other libraries thinking.
* has managed to create generic hierarchical diff that works for UI{Table,Collection}View. One level is trivial.
* acknowledges that UI{Table,Collection}View is a special case, so general diff is mostly useless.

I'm not sure I'll be in Tokyo any time soon, but if you ever come to Zurich, feel free to contact me and I'll buy you a 🍺.

**Comment by ra1028** [comment]
@kzaher
I understood your intention, and agreed.
I believe that your algorithm is the best ever among the libraries, and DifferenceKit too 👍 

Btw, Ids are not always determined by compile time.
For example, if the response of the API is incorrect, id may be duplicated the id in runtime.
In that case, the user may often wants to update the UI{Table,Collection}View by diff with best-effort rather than `reloadData`, IMO.
You might as well improve that point in RxDataSources.

Then, thank you for pointing out DifferenceKit's bug.
It seems I made a mistake when I refactored.
Correct is below.
```swift
static func == (lhs: TableKey, rhs: TableKey) -> Bool {
    return lhs.hashValue == rhs.hashValue
        && (lhs.pointer.distance(to: rhs.pointer) == 0 || lhs.pointer.pointee == rhs.pointer.pointee)
}
```

Anyway, the algorithm of RxDataSources is amazing.
I have no objection to refusing to replace it with DifferenceKit.

I can't wait to drink 🍺  with you.
Thanks.
