### ISSUE TITLE
Cannot invoke 'rx_itemsWithDataSource' with an argument list of type '(RxTableViewSectionedAnimatedDataSource<FileSections>)'

### ISSUE THREAD

**Issue by davidlondono** [RxSwiftCommunity/RxDataSources#43]
I folowed the instructions on the example and this is the error i got on:

```Swift
tableView.rx_itemsWithDataSource(dataSource)
```
error:
**Cannot invoke 'rx_itemsWithDataSource' with an argument list of type '(RxTableViewSectionedAnimatedDataSource<FileSections>)'**

**Comment by sergdort** [comment]
Hi, @davidlondono do you use with `bindTo` ?

**Comment by davidlondono** [comment]
yeah, i used it with it, and on a separated variable, and I got the error

**Comment by sergdort** [comment]
`rx_itemsWithDataSource` is currying function
```swift
public func rx_itemsWithDataSource<DataSource: protocol<RxTableViewDataSourceType, UITableViewDataSource>, S: SequenceType, O: ObservableType where DataSource.Element == S, O.E == S>
        (dataSource: DataSource)
        -> (source: O)
        -> Disposable
```
so It's need to know the type of `source` in order to please compiler :) 
If you would look on generic part `DataSource: protocol<RxTableViewDataSourceType, UITableViewDataSource>, S: SequenceType, O: ObservableType where DataSource.Element == S, O.E == S` it checks whether `DataSource.Element == S, O.E == S`

I guess if you want to use it in variable you need to annotate types

kinda :
```swift
let binder: (Observable<S>) -> Disposable = tableView.rx_itemsWithDataSource(dataSource)
```

**Comment by davidlondono** [comment]
ok, but still, on the bindTo it doesn't work

**Comment by sergdort** [comment]
Most likely it does not work because this constraint  `DataSource.Element == S, O.E == S`

Could you please provide more context (eg. code sipped, with annotated types)

**Comment by kzaher** [comment]
This seems stale.

**Comment by dangthaison91** [comment]
@davidlondono Please ensure that your `source` is `Observable<[Element]>`
