### ISSUE TITLE
Customize header view

### ISSUE THREAD

**Issue by leonereveel** [RxSwiftCommunity/RxDataSources#52]
Is there a way to customize the header view for RxTableViewDatasource?

**Comment by kzaher** [comment]
Hi,

since header customization is part of UITableViewDelegate, then the only way so far is to do
```swift
tableView.rx_setDelegate(someDelgateObjectPossiblyViewControllerImplementingUITableViewDelegate) // :(
    .addDisposableTo(disposeBag)
```

You can still access the bound data from RxTableViewDatasource by using 
```swift
self.dataSource.sectionAtIndex(index)
```

I have no idea why Apple decided to break apart those view factories into separate delegates.

¯\\\_(ツ)\_/¯ 

I'm thinking that maybe it would be a good idea to make future versions of RxTableViewDataSource conform to UITableViewDelegate also, and implement those closures.

**Comment by leonereveel** [comment]
Got it! I'm closing this issue but I think I can do a PR to implement this protocol too. It would be a great idea to make this datasource similar to the collection view one. :)
