### ISSUE TITLE
How to implement UITableViewRowAction?

### ISSUE THREAD

**Issue by Abel94** [RxSwiftCommunity/RxDataSources#76]
Hi, how to achieve UITableViewRowAction with rxdatasources?

**Comment by kzaher** [comment]
Hi @Abel94 ,

you can just do `rx.setDelegate(yourLegacyVC).addDisposableTo(disposeBag)` or `rx.setDataSource(yourLegacyVC).addDisposableTo(disposeBag)`.

That will enabled you to define necessary delegate/datasource methods the usual way and use this library.

**Comment by Abel94** [comment]
hi @kzaher 
Help me a lot! thank you very much!

**Comment by darrensapalo** [comment]
@kzaher Am I able to use both `rx.setDataSource` and `rx.items` at the same time? gave me an error saying that the data source has already been set.

My rationale is I am trying to set the data source's `tableView(_:canMoveRowAt:)` method to return `false` so that ordering is disabled. How would I go about that?
