### ISSUE TITLE
DifferentiatorError.duplicateItem breaks animation in unrelated sections of tableView

### ISSUE THREAD

**Issue by biboran** [RxSwiftCommunity/RxDataSources#81]
I was initializing one of my static AnimatableSectionModelType section as follows:

```swift
let someStaticSection: AnimatableMultipleSectionModel =
      .someStaticSection(
        title: "foo",
        items: (1...3).map{ _ in .staticSectionItem(image: UIImage(named: "myImage")!, title: "sample title") }
      )
```

and in another section that represents my observable data I was doing:

```swift
let observableSection: AnimatableMultipleSectionModel =
    .myDataSection(
      title: "my data",
      items: myObservableData.map{ .myDataSectionItem( \*some initialization here*\ ) }
    )
```

`.someStaticSection` was throwing `DifferentiatorError.duplicateItem` exception and I had animations broken in `.myDataSection`. I didn't notice the exception for quite a while and had no idea why the animations were not working. As soon as I replaced my `.someStaticSection` with differentiated  items the animations in `.myDataSection` started working.

I think it's an unintended behavior because unrelated sections should not affect animations of other sections within tableView. If duplicate items within a section is truly an exception behavior of the dataSource, shouldn't the program execution be aborted if the client doesn't catch the exception? And even if he does handle errors, why should business logic of sections initialization alter the way animations work?

**Comment by kzaher** [comment]
Hi @biboran ,

> I think it's an unintended behavior because unrelated sections should not affect animations of other sections within tableView.

We can animate any movements of items between sections, so uniqueness is important.

> If duplicate items within a section is truly an exception behavior of the dataSource, shouldn't the program execution be aborted if the client doesn't catch the exception? 

We had that behavior before, but since people don't read the docs they ended up crashing the app, not reading why it crashed and just being afraid to use the project because they thought we had some internal bugs that will cause crashes in production.

This is also meant to safeguard people from accidentally shipping their apps and crashing in production because they had duplicates and didn't understand the uniqueness requirement.

> And even if he does handle errors, why should business logic of sections initialization alter the way animations work?

Answer is above.
